### ISSUE TITLE
#UX Review

### ISSUE THREAD

**Issue by Dr4gon** [mai-soup/porch-reads-club#75]
@mai-soup Very nice instant validation on sign up 😍 Here's the first impression - I chose the wrong mic, therefore no audio. I commented on the important bits though: https://www.loom.com/share/48fa607d179d4da69f217f59d0ae180f

**Comment by mai-soup** [comment]
Alright, interesting. Few notes:

- Break in styling is because I've only done styling on the homepage, the rest of the site uses pico.css defaults. #53 
- Calls to action - fair enough, note taken. I want to redesign the whole libraries view, since
  1) owned libraries is a subset of memberships so there's a massive overlap
  2) needs a search functionality otherwise it's impossible to navigate as the list(s) grows (and users probably don't care for 99% of the "all" libraries anyway so why display them), and
  3) the map zoom is a bit arbitrary, i'll see if i can figure out a way to display user's country's bounding box in the view, as there'll be more of a chance of a library being visible then
- You sure you want your home address to be publicly visible now? :laughing: 
- I noticed you tried to search for the book in the format `[title] by [author]`, which didn't work partly because of mixing author and title, partly because of the "by" part, both of which the OpenLibrary API doesn't like.
  - I'll have a think about how to approach this - the "by" case is fairly easy, but if it's omitted, the mix is less so.

**Comment by mai-soup** [comment]
separated into own issues, closing for now
