### ISSUE TITLE
refactor to use async/await consistently

### ISSUE THREAD

**Issue by Dr4gon** [mai-soup/porch-reads-club#76]
@mai-soup I'm looking at your `LogInView.vue`. Have u considered using `.then()` and `.error()` from the promise?

```vue.js
   async performLogin() {
      try {
        await this.login({ username: this.identifier, password: this.password })
        this.$router.push({ name: 'home'})
      } catch (err) {
        console.error(err)
      }
    }
```

**Comment by Dr4gon** [comment]
I've been catching up on the [await vs. then usage](https://stackoverflow.com/questions/54495711/async-await-vs-then-which-is-the-best-for-performance) and my personal preference would be the then chaining because it allows you to

1. execute code after the then that's independent of the call
2. add catch to do the error handling with the request reponse as well

**Comment by Dr4gon** [comment]
@mai-soup I found a good example to illustrate where it would be useful to use the promise chain 

`profile-handler.js`

Your current version:

```vue.js
  actions: {
    async fetchProfile(username) {
      try {
        const response = await axios.get(`/users/${username}`)
        return response.data
      } catch (error) {
        // TODO: handle error
        console.error(error)
      }
    }
  }
```

My quickly refactored version:

```vue.js
  actions: {
    fetchProfile(username) {
      const response = axios.get(`/users/${username}`)
      .then((response) => {
        return response.data
      }).catch((error) => {
        console.error(error)
      })
    }
  }
```

**Comment by mai-soup** [comment]
I'm trying to stick to using `async/await` for consistency, to me it is easier to read and understand than `.then` (if anything, there's probably a couple places in the code where `.then` is still used, out of habit because that's what I learned first, and I should fix).

I'll take the liberty to leave this specific example as is, but leave the issue open until I'm sure there's no `.then`s left in the code that I can't elegantly refactor to `async/await`.
